#+OPTIONS: LaTeX:t          Do the right thing automatically (MathJax)
#+OPTIONS: LaTeX:dvipng     Force using dvipng images
#+OPTIONS: LaTeX:nil        Do not process LaTeX fragments at all
#+OPTIONS: LaTeX:verbatim   Verbatim export, for jsMath or so
#+ATTR_HTML: width="10in"

% org-export-with-LaTeX-fragments



README.org --- description



Copyright (C) 2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of sumowar.

  sumowar is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  sumowar is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with sumowar.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
  robot auto 




* Usage:
  use it



* History:
  Version 0.1 was created at 2013-05(May)-31

  

* Dependences:
  
* Description

  sumowar (амбиграмма)

   [[./drawings/sumowar.svg]]

  Основа робота - шасси с 4 ведущими и одновременно рулевыми
  колёсами. Угол поворота каждого колеса задаётся серводвигателем (180
  градусов). Поэтому робот может двигаться в любом направлении по
  плоскости, и с любым радиусом разворота.
  
  В качестве датчика линии - камера от оптической мыши.
  
  Для участия в битве роботов установлен переворачиватель
  противника. Пластиковая пластинка согнута под острым углом и играет роль отвала (ножа). Внутрь
  полученного угла установлен целофановый пакет. При приближении
  противника лодочный насос (12v) нагнетает воздух в целофановый
  пакет, он раздувается примерно за секунду (к сожалению обычно после
  этого пакет лопается - нужно добавить датчик давления для контроля
  процесса) и переворачивает робота противника. Эксперименты
  проводились на пятилитровой банке с водой по условиям конкурса вес
  робота не более 3кг.
  
  <2014.05(may).29> робот "sumowar" принял участие в конкурсе
  технологических решений роботизированных устройств «TechnoRoboCom»
  http://vk.com/club70185285 .
  
  В данный момент робот отдыхает на выставке СБИ-ПетрГУ.
  
  
  
  
  
* calculation
from http://www.robotshop.com/ca/learning-center/dynamic-tools.html
 
  | INPUT                   |          |
  |-------------------------+----------|
  | Total mass of robot:    | 3 kg     |
  | Number of drive motors: | 4 [#]    |
  | Radius of drive wheel:  | 0.015 M  |
  | Velocity of robot:      | 2 m/s    |
  | Maximum incline:        | 30 [deg] |
  | Supply voltage:         | 12 [V]   |
  | Desired acceleration:   | 0.2 m/s2 |
  | Desired operating time: | 15 min   |
  | Total efficiency:       | 65 [%]   |

  | OUTPUT  (per drive motor) |                                             |
  |---------------------------+---------------------------------------------|
  | Angular Velocity          | 133.33 rad/s                                |
  | Torque*                   | 0.088356  Nm, 0.90067 kgf-cm, 12.511 ozf-in |
  | Total Power               | 11.781 W                                    |
  | Maximum current           | 0.98173 [A]                                 |
  | Battery Pack              | 0.98173 [AH]                                |

  | DC/V | RPM/min | torque kg.cm | Reduction ratio(1:00) |
  |------+---------+--------------+-----------------------|
  | 12V  |     300 |          0.6 |                   100 |
  | 12V  |     200 |            1 |                   150 |
  | 12V  |     100 |            2 |                   298 |
  |      |         |              |                       |


* TechnoRoboCom 2014
  
  Один из основных этапов проекта - участие в конкурсе TechnoRoboCom
  организованном Студенческим Бизнес Инкубатором (СБИ ПетрГУ).

  В процессе работы в 2014 (второй семестр) году к проекту присоединились студенты.

  участники и их роли в проекте:
  
  | Ф.И.О.                       | факультет                    | специальность (1013-2014 годы)                                                              | роль в проекте                                                                                                    |
  |------------------------------+------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------|
  | Бирюков Алексей Сергеевич    | физико-технический факультет | Теплоэнергетика и теплотехника курс:1 21115                                                 | создание платы драйвера шагового двигателя, вилочный погрузчик с отвалом, "Презентация"                           |
  | Платонов Александр Сергеевич | физико-технический факультет | Теплоэнергетика и теплотехника курс:1 21115                                                 | создание платы драйвера шагового двигателя, вилочный погрузчик с отвалом, "Презентация"                           |
  | Угрюмов Андрей Николаевич    | физико-технический факультет | Электропривод и автоматика промышленных установок и технологических комплексов курс:5 21505 | алгоритм "Битва роботизированных устройств", "Презентация"                                                        |
  | Приходченко Роман Викторович | физико-технический факультет | Старший преподаватель                                                                       | всё остальное (закупки, механика, электроника, hal, алгоритм "Презентация", алгоритм "Трек", алгоритм "Лабиринт") |
 

* выводы

1. чтобы размещать платы стопками (как книги в шкафу) необходимо:
   
   печатные платы нужно делать с входами на одной стороне и выходами
   на другой стороне.
   
   совершенно недопустимо делать разъёмы на всех сторонах

2. на каждом этаже внутренней конструкции робота необходимо иметь
   "автономное" питание (свои GND, +5, +12)

3. каждый этаж должен соединяться со следующим ОДНИМ шлейфом (возможно
   составленным из проводов разного диаметра) чтобы можно было легко
   разъединять этажи

4. между устройствами (особенно между этажами) желательно использовать
   одну шину данных (i2c, 1-wire, ...), а не подключать каждое
   устройство напрямую к микроконтроллеру

5. ножки драйверов двигателей прижимать ?килоомным резистором к земле,
   а не оставлять болтаться как есть или подтягивать к питанию - чтобы
   при старте (в ту секунду между включением питания и инициализацией
   ножек микроконтроллера) двигатели не включались на полную скорость
