#+OPTIONS: LaTeX:t          Do the right thing automatically (MathJax)
#+OPTIONS: LaTeX:dvipng     Force using dvipng images
#+OPTIONS: LaTeX:nil        Do not process LaTeX fragments at all
#+OPTIONS: LaTeX:verbatim   Verbatim export, for jsMath or so
#+ATTR_HTML: width="10in"

% org-export-with-LaTeX-fragments



README.org --- description



Copyright (C) 2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of sumowar.

  sumowar is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  sumowar is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with sumowar.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
  robot auto 




* Usage:
  use it



* History:
  Version 0.1 was created at 2013-05(May)-31

  

* Dependences:
  
* Description


  sumowar [attachment=5]sumowar.png[/attachment]
  
  Основа робота - шасси с 4 ведущими и одновременно рулевыми
  колёсами. Угол поворота каждого колеса задаётся серводвигателем (180
  градусов). Поэтому робот может двигаться в любом направлении по
  плоскости, и с любым радиусом разворота.
  [attachment=4]chassis.png[/attachment]

  [attachment=3]14030037.jpg[/attachment]


  В качестве датчика линии - камера от оптической мыши.
  
  Для участия в битве роботов установлен переворачиватель
  противника. Пластиковая пластинка согнута под острым углом и играет
  роль отвала (ножа). Внутрь полученного отвала установлен целофановый
  пакет. При приближении противника лодочный насос (12v) нагнетает
  воздух в целофановый пакет, он надувается примерно за секунду и
  переворачивает робота противника. К сожалению, обычно, после этого
  пакет лопается - нужно добавить датчик давления для контроля
  процесса и отсос воздуха для многоразового
  использования. Эксперименты проводились на пятилитровой банке с
  водой (по условиям конкурса вес робота не более 3кг).
  [attachment=2]obstacle.png[/attachment]
  

  <2014.05(may).29> робот "sumowar" принял участие в конкурсе
  технологических решений роботизированных устройств «TechnoRoboCom»
  [url=http://vk.com/club70185285]«TechnoRoboCom»[/url] .
  [attachment=1]1auZE-fbeDQ.jpg[/attachment]
  [attachment=0]LDUvZ1TbqBs.jpg[/attachment]

  В данный момент робота забрали на выставку в СБИ-ПетрГУ  :sorry: .

  Исходные коды, чертежи и фотографии находятся по адресу:
  [url]https://github.com/chujoii/sumowar[/url]





Подробности о самоваре.

  
  Колёса собраны по второй схеме:
  [attachment=13]wheel.png[/attachment]
  
  Из следующих компонентов:
  [attachment=12]14020014.jpg[/attachment]
  
  [list]
  [*]Крепёж скоба металлическая однолапковая D=25mm[/*]
  [*]Подшипник с тонкими обоймами: от рулевой стойки 2108-09
    (C 2108-3401120-03) (размеры, как у 6805ZZ + пластиковая вставка)[/*]
  [*]Алюминиевый профиль квадратный, наружный размер 15x15мм,
    внутренний размер 12x12мм (подходит для двигателя)[/*]
  [*]12V 200RPM Mini DC Metal Gear Motor Model:N20 (Sanyo) вот здесь я
    промахнулся с выбором - нужно было покупать 5-вольтовые двигатели
    и к ним drv8830[/*]
  [*]покрышка для колеса подходящего диаметра[/*]
  [/list]
  
  Внутрь подшипника устанавливается алюминиевый профиль и всё
  закрепляется эпоксидкой (в проветриваемом помещении).  Самое
  сложное - сделать конструкцию соосной (не двигая головой, добиться
  чтобы при вращении подшипника отражения внутри алюминиевого профиля
  не наклонялись). 
  [attachment=11]14020037.jpg[/attachment]
  
  Скоба, маленький подшипник и пишущий узел от фломастера.
  [attachment=10]14030007.jpg[/attachment]
  
  На пластиковом основании (размеры отверстий соответствуют
  пластиковому конструктору) крепятся подшипники.
  [attachment=9]14030014.jpg[/attachment]

  С другой стороны приклеил держатели от банок с водой (розовые) и
  подходящего диаметра крышки (синие) - они играют роль сервосейверов,
  установщиков нуля (чтобы выставить поворот всех колёс одинаково) и
  стоек на которых крепятся серводвигатели.
  [attachment=8]14030006.jpg[/attachment]
  
  Собираем всё вместе: 
  [attachment=7]14030024.jpg[/attachment]

  Припаиваем провода и керамический конденсатор (например k10-176
  0.068uF U=50-100V), приклеиваем скобы на скотч, а также заклеиваем винт,
  чтобы он не прокручивался в пишущем узле от фломастера.
  [attachment=6]14030032.jpg[/attachment]


  Собираем всё вместе. На фотографии видны зажимы для бумаги - тоже
  своеобразные сервосейверы - они с одной стороны приклеены к
  покрышке, хорошо держатся на D-образном срезе оси двигателя, и
  должны прощёлкивать при превышении усилия (однако, как оказалось
  прощёлкивают даже при незначительном усилии и поэтому были сняты)
  [attachment=5]14030037.jpg[/attachment]
  
  Необходимо учитывать, что стандартные сервы могут разворачивать
  только на 180 градусов, а в некоторых случаях требуется
  реверсировать направление вращения двигателей. Формулы для расчётов:
  [attachment=4]motion.png[/attachment]


  Вот как выглядит первый слой после сборки
  (странности: фотография развёрнута):
  [attachment=3]14050005.jpg[/attachment]
  - чёрная плата в середине - видеокамера из оптической мыши (там был
    ещё микроконтроллер для предварительной обработки изображения, но
    он не влез по размерам и был отрезан)
  - самая верхняя и самая нижняя платы - L293 (знаю что не очень
    хорошие, но что было то и использовал)
  - справа из под видеокамеры выглядывают конденсаторы для
    серводвигателей с самовосстанавливающимися предохранителями на
    200мА
  - слева виден расширитель портов pcf8574 (выбор направления вращения
    для колёс) и шлейф (шина i2c + 1-wire + interrupt + reset)
  
  Включена подсветка поверхности для видеокамеры из мыши. В качестве
  объектива используется линза от CD-привода и дверной глазок.
  [attachment=2]14050009.jpg[/attachment]
  
  Помимо переворачивалки предполагался вилочный подъёмник, однако
  программная часть не была завершена вовремя и подъёмник не
  установили.
  [attachment=1]high-rise.png[/attachment]
  
  Одна из функций вилочного подъёмника - создание частичной
  невидимости.
  [attachment=0]invisible-and-military-dummy.png[/attachment]


  
  
  
  
* calculation
from http://www.robotshop.com/ca/learning-center/dynamic-tools.html
 
  | INPUT                   |          |
  |-------------------------+----------|
  | Total mass of robot:    | 3 kg     |
  | Number of drive motors: | 4 [#]    |
  | Radius of drive wheel:  | 0.015 M  |
  | Velocity of robot:      | 2 m/s    |
  | Maximum incline:        | 30 [deg] |
  | Supply voltage:         | 12 [V]   |
  | Desired acceleration:   | 0.2 m/s2 |
  | Desired operating time: | 15 min   |
  | Total efficiency:       | 65 [%]   |

  | OUTPUT  (per drive motor) |                                             |
  |---------------------------+---------------------------------------------|
  | Angular Velocity          | 133.33 rad/s                                |
  | Torque*                   | 0.088356  Nm, 0.90067 kgf-cm, 12.511 ozf-in |
  | Total Power               | 11.781 W                                    |
  | Maximum current           | 0.98173 [A]                                 |
  | Battery Pack              | 0.98173 [AH]                                |

  | DC/V | RPM/min | torque kg.cm | Reduction ratio(1:00) |
  |------+---------+--------------+-----------------------|
  | 12V  |     300 |          0.6 |                   100 |
  | 12V  |     200 |            1 |                   150 |
  | 12V  |     100 |            2 |                   298 |
  |      |         |              |                       |


* TechnoRoboCom 2014
  
  Один из основных этапов проекта - участие в конкурсе TechnoRoboCom
  организованном Студенческим Бизнес Инкубатором (СБИ ПетрГУ).

  В процессе работы в 2014 (второй семестр) году к проекту присоединились студенты.

  участники и их роли в проекте:
  
  | Ф.И.О.                       | факультет                    | специальность (1013-2014 годы)                                                              | роль в проекте                                                                                                    |
  |------------------------------+------------------------------+---------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------|
  | Бирюков Алексей Сергеевич    | физико-технический факультет | Теплоэнергетика и теплотехника курс:1 21115                                                 | создание платы драйвера шагового двигателя, вилочный погрузчик с отвалом, "Презентация"                           |
  | Платонов Александр Сергеевич | физико-технический факультет | Теплоэнергетика и теплотехника курс:1 21115                                                 | создание платы драйвера шагового двигателя, вилочный погрузчик с отвалом, "Презентация"                           |
  | Угрюмов Андрей Николаевич    | физико-технический факультет | Электропривод и автоматика промышленных установок и технологических комплексов курс:5 21505 | алгоритм "Битва роботизированных устройств", "Презентация"                                                        |
  | Приходченко Роман Викторович | физико-технический факультет | Старший преподаватель                                                                       | всё остальное (закупки, механика, электроника, hal, алгоритм "Презентация", алгоритм "Трек", алгоритм "Лабиринт") |


























[quote="AndreiSk"]А что он умеет делать?[/quote]

  Он ещё только учится :)
  
  Подготовка отдельных модулей к соревнованию длилась около года.
  Сборка была ужасной процедурой и заняла неделю. За оставшиеся два
  дня были протестированы только алгоритмы движения колёс и обработка
  изображения с видеокамеры.

  На конкурсе работали только следующие режимы:

  [list=1]
  [*] Презентация.  Робот, не поворачиваясь вокруг оси, рисует звёздочку
     "*" - проезжает по лучику и возвращается в центр.

     Потом вращается вокруг точек, которые генерируются в цикле.
     Координаты центров вращения расположены равномерно снаружи
     и внутри робота.[/*]
  
  [*] Отслеживание линии. Робот распознаёт линию видеокамерой,
     проезжает по ней около метра и теряет её :( Буду дорабатывать
     алгоритм позже.[/*]

  [*] Битва роботов. Не успел приделать датчики, алгоритм и вилочный
     подъёмник, поэтому был включён режим "презентации" с рисованием
     звёздочки и вращением. Робот выиграл два боя, случайно вытолкав
     противника с ринга во время танца  :oops: [/*]
  [/list]

  Сейчас робота забрали на выставку :( 
  Поэтому доделываю недоделки:  сканирующую систему для построения карты
  и поиска противников.

[quote="AndreiSk"]Видео может какое есть?  :)[/quote]  
  
  [youtube]cjYzR39-Q50[/youtube]
  выступление самовара с 2:26

  [url]http://vk.com/video-60211626_169279477[/url]


















* выводы

1. чтобы размещать платы стопками (как книги в шкафу) необходимо:
   
   печатные платы нужно делать с входами на одной стороне и выходами
   на другой стороне.
   
   совершенно недопустимо делать разъёмы на всех сторонах

2. на каждом этаже внутренней конструкции робота необходимо иметь
   "автономное" питание (свои GND, +5, +12)

3. каждый этаж должен соединяться со следующим ОДНИМ шлейфом (возможно
   составленным из проводов разного диаметра) чтобы можно было легко
   разъединять этажи

4. между устройствами (особенно между этажами) желательно использовать
   одну шину данных (i2c, 1-wire, ...), а не подключать каждое
   устройство напрямую к микроконтроллеру

5. ножки драйверов двигателей прижимать ?килоомным резистором к земле,
   а не оставлять болтаться как есть или подтягивать к питанию - чтобы
   при старте (в ту секунду между включением питания и инициализацией
   ножек микроконтроллера) двигатели не включались на полную скорость
