* url

http://www.petrsu.ru/Structure/Innov_vr/news.html?action=theme&tid=50

http://vk.com/ptzschoolsit

http://vk.com/technorobocom

http://vk.com/sbi_petrsu

http://vk.com/konovalov_ap

http://www.petrsu.ru/Structure/SBI/announce.html?action=division&did=510

https://twitter.com/SBIpetrsu

http://vk.com/club70185285

http://www.petrsu.ru/print.html?action=preview&id=14343

http://vk.com/fig_petrsu

* reglament
  <2014-05-20 Tue 17:33>
  Вопрос по регламенту:
  
  Участие в конкурсе предполагает несколько этапов:
1. Презентация роботизированного устройства (или командной идеи).
   Форма презентации - произвольная. Это может быть что угодно,
   например, роботизированое устройство что-то делает ( катание робота
   под музыку или поет😊 или представитель команды презентует свое
   устройство (очень мило, если будет в юморном формате) и т.д.
2. «Трек» (условия состязания см. ниже в новостях);
3. «Лабиринт».
4. «Битва роботизированных устройств».

На каждом этапе начисляются очки, так, что победит сильнейший.


  <2014-04-22 Tue 20:36>

  Предварительный РЕГЛАМЕНТ проведения
  соревнования в рамках конкурса технологических решений в области
  робототехники «TechnoRoboCom. Взрослая Лига 2014»
  
**  ------------------------------Этапы соревнования--------------------------
  
1. «Трек». Условия состязания:

   * двигаясь по треку, роботизированное устройство должно добраться от
   старта до финиша. Во время старта робот должен находиться в зоне
   старта (передняя часть перед стартовой чертой);

   * максимальное время для выполнения составляет 5 минут. Время гонки
   измеряется с момента старта робота со стартовой зоны и до того
   момента, когда передняя часть тела робота пересечёт финишную черту;

   * трек представляет собой матовую черную линию, шириной 20 мм. Трек
   состоит из:

   - линия старта и финиша;

   - прямые участки;

   - закругления, внутренним радиусом не менее 150 мм;

   - пересечения линий трека под прямым углом.

  * игровой трек разделен на зоны, выделяемые поперечными линиями,
   длиной 100 мм;

  * длина игрового поля для гонки - не более 3 м, ширина поля - не
   более 2 м;

  * игровое поле имеет искусственные неровности с углами продольного
   наклона – не более 15 гр. и поперечного – не более 30 гр.;

  * цвет игрового поля – белый;

  * окончательный вариант игрового трека представляется в день
   проведения конкурса. Перед проведением конкурса участники команд
   могут тренироваться на усеченном формате трека.

2. «Лабиринт». Условия состязания:

  * двигаясь вдоль линии (ширина 20 мм) роботизированное устройство
   должно найти единственно верный путь от старта до финиша;

  * все линии пересекаются под углом в 90 гр.;

  * игровой трек разделен на несколько зон, выделяемых поперечными
   линиями.

3. «Битва роботизированных устройств». Условия состязания:

  * состязание происходит на круглом ринге диаметром 1 м.;

  * во время начала состязания устройства должны находиться в зоне
   старта;

  * после старта устройства должны либо сдвинуть устройство противника
   за пределы ринга, либо обеспечить невозможность последующих
   действий противника по выполнению условий конкурса в течение 20
   секунд;

  * в случае, если оба соперника не двигаются в течение 30 секунд, то
   засчитывается ничья.

** --------------Требования к роботизированному устройству-------------

1. Максимальная длина х ширина х высота робота: 500 х 500 х 450 мм.

2. Колёсную базу можно модернизировать.

3. Во время состязаний устройство может менять свои размеры.

4. При создании программы допускается использование любого
   программного обеспечения.

5. Количество двигателей и датчиков не ограничено.

6. Вес – не более 3 кг
